"""Session repository interface."""

from abc import ABC, abstractmethod
from typing import List, Optional
from uuid import UUID

from app.domain.entities import Session
from app.domain.value_objects import SessionStatus


class SessionRepository(ABC):
    """
    Abstract repository interface for Session entities.

    This interface defines the contract for session persistence without
    specifying the implementation (could be PostgreSQL, SQLite, in-memory, etc.)

    The repository follows the Repository pattern from Domain-Driven Design,
    acting as an in-memory collection abstraction over the data store.
    """

    @abstractmethod
    async def create(self, session: Session) -> Session:
        """
        Create and persist a new session.

        Args:
            session: Session entity to create. The ID may be pre-assigned or
                    generated by the implementation.

        Returns:
            Created session with ID assigned (if not already set) and any
            database-generated fields populated.

        Raises:
            RepositoryError: If creation fails due to database errors.
        """
        pass

    @abstractmethod
    async def get_by_id(self, session_id: UUID) -> Optional[Session]:
        """
        Retrieve session by ID.

        Args:
            session_id: UUID of the session to retrieve.

        Returns:
            Session entity if found, None otherwise.

        Raises:
            RepositoryError: If query fails due to database errors.
        """
        pass

    @abstractmethod
    async def get_by_project_id(
        self, project_id: UUID, include_deleted: bool = False
    ) -> List[Session]:
        """
        Get all sessions associated with a project.

        Args:
            project_id: UUID of the project.
            include_deleted: Whether to include soft-deleted sessions.
                           Defaults to False.

        Returns:
            List of sessions for the project (may be empty).
            Sessions are not guaranteed to be in any particular order.

        Raises:
            RepositoryError: If query fails due to database errors.
        """
        pass

    @abstractmethod
    async def get_active_sessions(self) -> List[Session]:
        """
        Get all active (non-terminal) sessions.

        Active sessions are those not in terminal states (COMPLETED, ERROR, CANCELLED).

        Returns:
            List of active sessions (may be empty).

        Raises:
            RepositoryError: If query fails due to database errors.
        """
        pass

    @abstractmethod
    async def get_by_status(self, status: SessionStatus) -> List[Session]:
        """
        Get sessions by status.

        Args:
            status: Session status to filter by.

        Returns:
            List of sessions with the given status (may be empty).

        Raises:
            RepositoryError: If query fails due to database errors.
        """
        pass

    @abstractmethod
    async def update(self, session: Session) -> Session:
        """
        Update existing session.

        The session entity should have been retrieved from this repository
        and modified using its business methods.

        Args:
            session: Session entity with updated values. Must have a valid ID.

        Returns:
            Updated session with any database-generated fields refreshed.

        Raises:
            NotFoundError: If session with given ID doesn't exist.
            RepositoryError: If update fails due to database errors.
        """
        pass

    @abstractmethod
    async def delete(self, session_id: UUID) -> None:
        """
        Soft-delete a session.

        Sets the deleted_at timestamp without removing the record from the database.

        Args:
            session_id: UUID of session to delete.

        Raises:
            NotFoundError: If session with given ID doesn't exist.
            RepositoryError: If deletion fails due to database errors.
        """
        pass

    @abstractmethod
    async def exists(self, session_id: UUID) -> bool:
        """
        Check if session exists (including soft-deleted sessions).

        Args:
            session_id: UUID of session to check.

        Returns:
            True if session exists (even if soft-deleted), False otherwise.

        Raises:
            RepositoryError: If query fails due to database errors.
        """
        pass

    @abstractmethod
    async def get_latest_pm_session(self, project_id: UUID) -> Optional[Session]:
        """
        Get the latest PM session for a project.

        Retrieves the most recently created PM session that is not deleted.
        This is useful for specialists to find their project manager, and will
        support PM restart/recreate scenarios where a new PM replaces an old one.

        Args:
            project_id: UUID of the project to find PM session for.

        Returns:
            The latest PM session entity, or None if no PM found.

        Raises:
            RepositoryError: If query fails due to database errors.
        """
        pass
